//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int id { get; set; }
        public int factura_id { get; set; }
        public int servicio_id { get; set; }
        public int tecnico_id { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
